### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by JohnatanT** [piomin/spring-boot-logging#10]
The following error appears to me:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logstashAppender' defined in class path resource [pl/piomin/logging/config/SpringLoggingAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [net.logstash.logback.appender.LogstashTcpSocketAppender]: Factory method 'logstashAppender' threw exception; nested exception is java.lang.NullPointerException

Once you have enabled:
`logging.logstash.enabled = true`

I added Breakpoint and verified that it shows the error when arriving here:

trustStoreLocation.ifPresent(it -> {         //Line 71

**Comment by piomin** [comment]
Fixed in version 1.2.2
