### ISSUE TITLE
When Using spring-cloud-starter-bus-amqp along with logstash-logging-spring-boot-starter, logs are not showing in Kibana.

### ISSUE THREAD

**Issue by ubaid4j** [piomin/spring-boot-logging#22]
## Backgroud
I have a rest-api in which I am using
- `spring-cloud-starter-config`
- `spring-cloud-starter-bus-amqp`
and then I used
- `logstash-logging-spring-boot-starter`

Now I cannot see the logs in Kibana dashboard. When I remove `spring-cloud-starter-bus-amqp` then logs are being showed in Kibana dashboard. 

I guess there is something wrong in between `spring-cloud-starter-bus-amqp` and `logstash-logging-spring-boot-starter`

## Expected Result
I should able to use `logstash-logging-spring-boot-starter` with `spring-cloud-starter-bus-amqp` and logs should have shown. 

## Prerequisite
- Java 15
- Maven 3.6.3
- Docker 19

## How to reproduce the problem:
- `git clone https://github.com/UbaidurRehman1/Cloud-Native-App-Spring-Boot.git`
- `cd Cloud-Native-App-Spring-Boot`
- `git checkout issues/#146`
- `mvn clean install -DskipTests`
- `cd envcn`
- `./run.sh` (this will up all tools which are required for our services like ELK stack, config server, zipkin and rabbit-mq)
- `cd ..`
- `./run.sh` (this will up our services like rest-api) 
- [Go to Kibana Dashboard](http://localhost:5601/app/discover#/)
- [First setupt the kibana dashboard](https://github.com/UbaidurRehman1/Cloud-Native-App-Spring-Boot#kibana-dashboard-for-centralized-logging)
- [Now go to Swagger UI](http://localhost:5200/swagger-ui/index.html#/exchange-controller/getCurrencyConversionUsingGET)
- Execute this controller by putting in `from` field `USD`, in `to` field `PKR` and in `quantity` field `10`
- Now check the logs, there are only logs of services. There is no log about rest-api. (I have added this combination  `logstash-logging-spring-boot-starter` with `spring-cloud-starter-bus-amqp` only in rest-api) 

### Profile
- The above services will run in dev profile
- [You can access them](https://github.com/UbaidurRehman1/public-repo)

**Comment by piomin** [comment]
I don't know what you expect from that library.  It has an auto-configured connection to logstash. I can add an option for an auto-configured connection to AMQP. But you still need to get logs from AMQP (e.g. RabbitMQ) and export them to logstash or elastic. It won't be done on the application side.

Here you have an example with AMQP logging for Spring Boot: https://github.com/piomin/sample-amqp-logging.git.

**Comment by piomin** [comment]
i'm closing the issue due to inactivity
