### ISSUE TITLE
Consider stop using `spring.*` configuration namespace

### ISSUE THREAD

**Issue by snicoll** [piomin/spring-boot-logging#3]
As described [in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-configuration-keys), we ask third party integration not to reuse official namespace for configuration.

Side note, rather than using `@Value` it would be nice to use `ConfigurationProperties` and the annotation processor to get proper metadata for IDE support.

**Comment by piomin** [comment]
fixed
