### ISSUE TITLE
Http request lose params from POST body after read it once

### ISSUE THREAD

**Issue by SYanalyser** [piomin/spring-boot-logging#31]
@RequestParam is null

**Comment by piomin** [comment]
Well, I created a dedicated test for that. Can you take a look here: logging-spring-tests/src/test/java/com/github/piomin/MainControllerTests.java? (`postByIdReqParam()` method). The test is successful for such an endpoint:
```
@PostMapping("/req-param")
public String postWithIdRequest(@RequestParam Integer id) {
    return "Hello-" + id;
}
```

**Comment by SYanalyser** [comment]
Try this out？
curl --location 'localhost:8080/test/req-param' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'id=1'

**Comment by SYanalyser** [comment]
If you remove the 'logstash-logging-spring-boot-starter' dependency and try again, you will get different results@piomin
