### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by bihu1** [piomin/spring-boot-logging#7]
I'd like to download and use your library by maven. You specify maven dependency in your article, but I cannot find information about online repository it is available. Can you add this information in readme or show me if I just overlooked it.

**Comment by piomin** [comment]
I published the library on Maven Central.
```
<dependency>
  <groupId>com.github.piomin</groupId>
  <artifactId>logstash-logging-spring-boot-starter</artifactId>
  <version>1.2.1.RELEASE</version>
</dependency>
```
